# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  jackson:
    serialization.indent_output: true
  boot:
    admin:
      client:
        enabled: false
        username: admin
        password: admin
        url: "http://localhost:11080"

info:
  env: ${ENV_TYPE:dev}
  config: ${CONFIG_TYPE:dev}
  service:
    name: ${spring.application.name}
    host: ${HOST:localhost}
    port: ${server.port}

logging:
  level:
    ROOT: INFO
