# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  liquibase:
    enabled: false
  profiles:
    active: dev
  jackson:
    serialization.indent_output: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:oracle:thin:@sgsioradbuat.saint-gobain.com:1521:WAPR
    username: APP_PEGR_OWNER
    password: AppP$gR0wner01
    hikari:
      jdbc-url: jdbc:oracle:thin:@sgsioradbuat.saint-gobain.com:1521:WAPR
      username: APP_PEGR_OWNER
      password: AppP$gR0wner01
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle12cDialect
    database: ORACLE
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: assetid
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  mail:
    host: localhost
    username:
    password:
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    protocol: smtp
    test-connection: false
  servlet:
    multipart:
      location: 'C:\tmp'
  boot:
    admin:
      client:
        enabled: false

saint:
  gobain:
    swagger:
      default-include-pattern: pcpeg.*
    security:
      exposure:
        exclude:
          - /companies/**
    pcpeg:
      commonLocation: 'C:\dev\pcpeg'
      frontend-url: https://uat.pcpeg.saint-gobain.com
      directory:
        url: https://lan.api.saint-gobain.com/sgdsi/test
        keyId: 101cc044-e048-4475-adeb-ccb4c3d5d060
      mail:
        enabled: true